---
- name: "create ipsec conf files"
  ansible.builtin.template:
    src: connection.conf
    dest: "/etc/ipsec.d/{{ item.key }}.conf"
    mode: '0644'
  loop: "{{ ipsec_connections | dict2items }}"
  register: ipsec_connections_creation
  notify: "{{ ipsec_handler }}"

- name: "create ipsec secrets files"
  ansible.builtin.template:
    src: connection.secrets
    dest: "/etc/ipsec.d/{{ item.key }}.secrets"
    mode: '0600'
  loop: "{{ ipsec_connections | dict2items }}"
  register: ipsec_secrets_creation
  notify: "{{ ipsec_handler }}"
