---
dependency:
  name: galaxy
  enabled: false
  options:
    role-file: requirements.yml
driver:
  name: vagrant
  provider:
    name: virtualbox
platforms:
  - name: test-gw-1
    box: centos/7
    memory: 512
    cpus: 1
    interfaces:
      - auto_config: true
        network_name: private_network
        type: static
        ip: 172.16.100.17
    instance_raw_config_args:
      - "vm.network 'private_network', ip: '192.168.1.1', virtualbox__intnet: true"
  - name: test-gw-2
    box: debian/buster64
    memory: 512
    cpus: 1
    interfaces:
      - auto_config: true
        network_name: private_network
        type: static
        ip: 172.16.100.33
    instance_raw_config_args:
      - "vm.network 'private_network', ip: '192.168.2.1', virtualbox__intnet: true"
provisioner:
  name: ansible
  log: True
  config_options:
    defaults:
      callbacks_enabled: ansible.posix.profile_tasks
verifier:
  name: testinfra
  options:
    verbose: true
    p: 'no:pytest-ansible'
